import { Product } from "@/types";

export type { Product };

export const categories = [
  "Templates",
  "Ebooks",
  "Courses",
  "Tools",
  "Graphics",
  "Audio",
];

export const allProducts: Product[] = [
  {
    id: "1",
    name: "Premium UI Kit",
    slug: "premium-ui-kit",
    description: "A comprehensive UI kit with over 500 components, designed for modern web applications. Includes dark mode, responsive layouts, and extensive customization options.",
    short_description: "500+ modern UI components with dark mode and responsive layouts",
    price: 49.99,
    compare_at_price: 79.99,
    image_url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&q=80",
    preview_images: [
      "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&q=80",
      "https://images.unsplash.com/photo-1558655146-d09347e0b708?w=800&q=80",
    ],
    category_id: "1",
    category: {
      id: "1",
      slug: "templates",
      name: "Templates",
      sort_order: 1,
    },
    tags: ["bestseller", "featured"],
    product_type: "template",
    featured: true,
    status: "published",
    sales_count: 2500,
    rating: 4.9,
    review_count: 128,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "2",
    name: "SaaS Landing Page",
    slug: "saas-landing-page",
    description: "High-converting landing page template for SaaS products. Built with Next.js, Tailwind CSS, and includes conversion-optimized sections.",
    short_description: "Conversion-optimized landing page for SaaS products",
    price: 39.99,
    image_url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80",
    preview_images: ["https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80"],
    category_id: "1",
    category: {
      id: "1",
      slug: "templates",
      name: "Templates",
      sort_order: 1,
    },
    tags: ["bestseller"],
    product_type: "template",
    featured: true,
    status: "published",
    sales_count: 1800,
    rating: 4.8,
    review_count: 96,
    created_at: "2024-01-02T00:00:00Z",
  },
  {
    id: "3",
    name: "E-commerce Dashboard",
    slug: "ecommerce-dashboard",
    description: "Complete admin dashboard template for e-commerce platforms. Real-time analytics, order management, and inventory tracking.",
    short_description: "Admin dashboard with analytics and order management",
    price: 59.99,
    compare_at_price: 89.99,
    image_url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80",
    preview_images: ["https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80"],
    category_id: "1",
    category: {
      id: "1",
      slug: "templates",
      name: "Templates",
      sort_order: 1,
    },
    tags: ["featured"],
    product_type: "template",
    featured: true,
    status: "published",
    sales_count: 1200,
    rating: 4.7,
    review_count: 84,
    created_at: "2024-01-03T00:00:00Z",
  },
  {
    id: "4",
    name: "Design System Pro",
    slug: "design-system-pro",
    description: "Enterprise-grade design system with tokens, components, and documentation. Perfect for scaling design across teams.",
    short_description: "Enterprise design system with tokens and components",
    price: 99.99,
    image_url: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&q=80",
    preview_images: ["https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&q=80"],
    category_id: "1",
    category: {
      id: "1",
      slug: "templates",
      name: "Templates",
      sort_order: 1,
    },
    tags: ["bestseller", "featured"],
    product_type: "template",
    featured: true,
    status: "published",
    sales_count: 950,
    rating: 5.0,
    review_count: 64,
    created_at: "2024-01-04T00:00:00Z",
  },
  {
    id: "5",
    name: "The Digital Nomad",
    slug: "digital-nomad-ebook",
    description: "Master the art of remote work with this comprehensive guide. Learn how to build a location-independent career.",
    short_description: "Complete guide to building a location-independent career",
    price: 19.99,
    image_url: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&q=80",
    preview_images: ["https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&q=80"],
    category_id: "2",
    category: {
      id: "2",
      slug: "ebooks",
      name: "Ebooks",
      sort_order: 2,
    },
    tags: ["bestseller"],
    product_type: "ebook",
    featured: false,
    status: "published",
    sales_count: 3200,
    rating: 4.8,
    review_count: 215,
    created_at: "2024-01-05T00:00:00Z",
  },
  {
    id: "6",
    name: "Marketing Mastery",
    slug: "marketing-mastery",
    description: "The ultimate guide to digital marketing in 2024. Covers SEO, social media, email marketing, and paid advertising.",
    short_description: "Ultimate guide to digital marketing in 2024",
    price: 29.99,
    compare_at_price: 49.99,
    image_url: "https://images.unsplash.com/photo-1553484771-371a605b060b?w=800&q=80",
    preview_images: ["https://images.unsplash.com/photo-1553484771-371a605b060b?w=800&q=80"],
    category_id: "2",
    category: {
      id: "2",
      slug: "ebooks",
      name: "Ebooks",
      sort_order: 2,
    },
    tags: ["featured"],
    product_type: "ebook",
    featured: true,
    status: "published",
    sales_count: 1500,
    rating: 4.6,
    review_count: 178,
    created_at: "2024-01-06T00:00:00Z",
  },
  {
    id: "7",
    name: "Startup Playbook",
    slug: "startup-playbook",
    description: "From idea to IPO: the complete guide for entrepreneurs. Includes frameworks, templates, and real case studies.",
    short_description: "Complete entrepreneurial guide from idea to IPO",
    price: 34.99,
    image_url: "https://images.unsplash.com/photo-1553028826-f4804a6dba3b?w=800&q=80",
    preview_images: ["https://images.unsplash.com/photo-1553028826-f4804a6dba3b?w=800&q=80"],
    category_id: "2",
    category: {
      id: "2",
      slug: "ebooks",
      name: "Ebooks",
      sort_order: 2,
    },
    tags: ["bestseller"],
    product_type: "ebook",
    featured: false,
    status: "published",
    sales_count: 2100,
    rating: 4.9,
    review_count: 142,
    created_at: "2024-01-07T00:00:00Z",
  },
  {
    id: "8",
    name: "React Advanced Patterns",
    slug: "react-advanced-patterns",
    description: "Master advanced React patterns and performance optimization techniques. For experienced developers ready to level up.",
    short_description: "Master advanced React patterns and optimizations",
    price: 79.99,
    image_url: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800&q=80",
    preview_images: ["https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800&q=80"],
    category_id: "3",
    category: {
      id: "3",
      slug: "courses",
      name: "Courses",
      sort_order: 3,
    },
    tags: ["bestseller", "featured"],
    product_type: "bundle",
    featured: true,
    status: "published",
    sales_count: 4200,
    rating: 4.9,
    review_count: 312,
    created_at: "2024-01-08T00:00:00Z",
  },
  {
    id: "9",
    name: "UI/UX Design Fundamentals",
    slug: "ui-ux-fundamentals",
    description: "Comprehensive design course covering user research, wireframing, prototyping, and design systems.",
    short_description: "Complete UI/UX design course from basics to advanced",
    price: 69.99,
    compare_at_price: 99.99,
    image_url: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&q=80",
    preview_images: ["https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&q=80"],
    category_id: "3",
    category: {
      id: "3",
      slug: "courses",
      name: "Courses",
      sort_order: 3,
    },
    tags: ["featured"],
    product_type: "bundle",
    featured: true,
    status: "published",
    sales_count: 1800,
    rating: 4.7,
    review_count: 198,
    created_at: "2024-01-09T00:00:00Z",
  },
  {
    id: "10",
    name: "Figma Plugin Pack",
    slug: "figma-plugin-pack",
    description: "Essential plugins for Figma power users. Includes color tools, component generators, and workflow automations.",
    short_description: "Essential plugins for Figma power users",
    price: 24.99,
    image_url: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&q=80",
    preview_images: ["https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&q=80"],
    category_id: "4",
    category: {
      id: "4",
      slug: "tools",
      name: "Tools",
      sort_order: 4,
    },
    tags: [],
    product_type: "template",
    featured: false,
    status: "published",
    sales_count: 950,
    rating: 4.5,
    review_count: 87,
    created_at: "2024-01-10T00:00:00Z",
  },
  {
    id: "11",
    name: "Icon Library Pro",
    slug: "icon-library-pro",
    description: "10,000+ premium icons in multiple styles. Includes SVG, PNG, and font formats with Figma components.",
    short_description: "10,000+ premium icons in multiple formats",
    price: 39.99,
    image_url: "https://images.unsplash.com/photo-1618556450994-a6a128ef0d9d?w=800&q=80",
    preview_images: ["https://images.unsplash.com/photo-1618556450994-a6a128ef0d9d?w=800&q=80"],
    category_id: "5",
    category: {
      id: "5",
      slug: "graphics",
      name: "Graphics",
      sort_order: 5,
    },
    tags: ["bestseller"],
    product_type: "template",
    featured: false,
    status: "published",
    sales_count: 2800,
    rating: 4.8,
    review_count: 156,
    created_at: "2024-01-11T00:00:00Z",
  },
  {
    id: "12",
    name: "Stock Photo Bundle",
    slug: "stock-photo-bundle",
    description: "500+ high-quality stock photos for commercial use. Covers business, technology, lifestyle, and nature.",
    short_description: "500+ high-quality stock photos for commercial use",
    price: 29.99,
    compare_at_price: 59.99,
    image_url: "https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=800&q=80",
    preview_images: ["https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=800&q=80"],
    category_id: "5",
    category: {
      id: "5",
      slug: "graphics",
      name: "Graphics",
      sort_order: 5,
    },
    tags: [],
    product_type: "template",
    featured: false,
    status: "published",
    sales_count: 1600,
    rating: 4.6,
    review_count: 124,
    created_at: "2024-01-12T00:00:00Z",
  },
  {
    id: "13",
    name: "Music Producer Kit",
    slug: "music-producer-kit",
    description: "Professional audio loops, samples, and presets for music production. Compatible with all major DAWs.",
    short_description: "Professional audio loops and samples for music production",
    price: 49.99,
    image_url: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=800&q=80",
    preview_images: ["https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=800&q=80"],
    category_id: "6",
    category: {
      id: "6",
      slug: "audio",
      name: "Audio",
      sort_order: 6,
    },
    tags: ["bestseller"],
    product_type: "bundle",
    featured: false,
    status: "published",
    sales_count: 1900,
    rating: 4.7,
    review_count: 203,
    created_at: "2024-01-13T00:00:00Z",
  },
  {
    id: "14",
    name: "Podcast Starter Pack",
    slug: "podcast-starter-pack",
    description: "Everything you need to start a professional podcast. Templates, intro music, and editing presets included.",
    short_description: "Complete kit to start a professional podcast",
    price: 34.99,
    image_url: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=800&q=80",
    preview_images: ["https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=800&q=80"],
    category_id: "6",
    category: {
      id: "6",
      slug: "audio",
      name: "Audio",
      sort_order: 6,
    },
    tags: [],
    product_type: "bundle",
    featured: false,
    status: "published",
    sales_count: 1100,
    rating: 4.5,
    review_count: 89,
    created_at: "2024-01-14T00:00:00Z",
  },
  {
    id: "15",
    name: "Code Snippet Library",
    slug: "code-snippet-library",
    description: "Curated collection of production-ready code snippets. React, TypeScript, Python, and more with documentation.",
    short_description: "Production-ready code snippets with documentation",
    price: 19.99,
    image_url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80",
    preview_images: ["https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80"],
    category_id: "4",
    category: {
      id: "4",
      slug: "tools",
      name: "Tools",
      sort_order: 4,
    },
    tags: ["bestseller"],
    product_type: "template",
    featured: false,
    status: "published",
    sales_count: 3500,
    rating: 4.8,
    review_count: 267,
    created_at: "2024-01-15T00:00:00Z",
  },
  {
    id: "16",
    name: "Video Transition Pack",
    slug: "video-transition-pack",
    description: "Cinematic video transitions for Premiere Pro and Final Cut Pro. 100+ seamless transitions for any project.",
    short_description: "100+ cinematic video transitions for video editors",
    price: 44.99,
    compare_at_price: 69.99,
    image_url: "https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800&q=80",
    preview_images: ["https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800&q=80"],
    category_id: "5",
    category: {
      id: "5",
      slug: "graphics",
      name: "Graphics",
      sort_order: 5,
    },
    tags: [],
    product_type: "template",
    featured: false,
    status: "published",
    sales_count: 1400,
    rating: 4.7,
    review_count: 134,
    created_at: "2024-01-16T00:00:00Z",
  },
];

// Get featured products
export function getFeaturedProducts(): Product[] {
  return allProducts.filter((p) => p.featured);
}

// Get bestsellers
export function getBestsellers(): Product[] {
  return allProducts.filter((p) => p.tags?.includes("bestseller"));
}

// Get products by category
export function getProductsByCategory(category: string): Product[] {
  if (category === "All") return allProducts;
  return allProducts.filter((p) => p.category?.name === category);
}

// Get product by slug
export function getProductBySlug(slug: string): Product | undefined {
  return allProducts.find((p) => p.slug === slug);
}
